const path = require('path')
const express = require('express')
const bodyParser = require('body-parser')
const adminRoutes = require('./routes/admin')
const shopRoutes = require('./routes/shop')
const notFoundRoutes = require('./routes/404')

const app = express()
app.set('view engine', 'ejs')
app.set('views', 'views')

app.use(bodyParser.urlencoded({extended: true}))
app.use(express.static(path.join(__dirname, 'public')))
app.use('/admin', adminRoutes)
app.use(shopRoutes)
// app.use((req, res, next) => {
//     res.status(404).sendFile(path.join(__dirname,'views', '404.html'))
// })
app.use(notFoundRoutes)
app.listen(3001)